INSERT INTO "ShipSchema"."TB_TYPE_NAVIRE"(libelle) VALUES ('PETROLIER');
INSERT INTO "ShipSchema"."TB_TYPE_NAVIRE"(libelle) VALUES ('GAZIER');
INSERT INTO "ShipSchema"."TB_TYPE_NAVIRE"(libelle) VALUES ('CHIMIQUIER');
INSERT INTO "ShipSchema"."TB_TYPE_NAVIRE"(libelle) VALUES ('VRAQUIER SOLIDE');
INSERT INTO "ShipSchema"."TB_TYPE_NAVIRE"(libelle) VALUES ('PINARDIER');
INSERT INTO "ShipSchema"."TB_TYPE_NAVIRE"(libelle) VALUES ('MELASSIER');
INSERT INTO "ShipSchema"."TB_TYPE_NAVIRE"(libelle) VALUES ('HUILIER');
INSERT INTO "ShipSchema"."TB_TYPE_NAVIRE"(libelle) VALUES ('AUTRE');
